INSERT INTO public.eco_news(
    creation_date, author_id, text, title, source, short_info)
VALUES ('2022-06-27 12:28:31', 2, 'New farms that support natural environment and help protect animals against abuse', 'news about farm', 'farm source', 'Short info farms'),
       ('2021-06-27 15:15:42', 2, 'New fuel made from fertilizer storms the market!', 'news about fuel', 'fuel source', 'short info fuel'),
       ('2022-03-24 11:14:12', 2, 'Usage of plastic straws in gastronomic industry has been falling since 2016', 'news about straws', 'straws source', 'short info straws'),
       ('2022-07-08 21:22:31', 2, 'With more eco-friendly approach to shopping, biggest EU markets noted an increase in sales of paper bags', 'news about paperbags', 'bags source', 'short info bags'),
       ('2020-06-27 12:28:31', 4, 'New farms that support natural environment and help protect animals against abuse', 'news about farm', 'farm source', 'Short info farms'),
       ('2020-06-27 15:15:42', 4, 'New fuel made from fertilizer storms the market!', 'news about fuel', 'fuel source', 'short info fuel'),
       ('2020-03-24 11:14:12', 4, 'Usage of plastic straws in gastronomic industry has been falling since 2016', 'news about straws', 'straws source', 'short info straws'),
       ('2020-07-08 21:22:31', 4, 'With more eco-friendly approach to shopping, biggest EU markets noted an increase in sales of paper bags', 'news about paperbags', 'bags source', 'short info bags'),
       ('2019-06-27 12:28:31', 5, 'New farms that support natural environment and help protect animals against abuse', 'news about farm', 'farm source', 'Short info farms'),
       ('2019-06-27 15:15:42', 5, 'New fuel made from fertilizer storms the market!', 'news about fuel', 'fuel source', 'short info fuel'),
       ('2019-03-24 11:14:12', 5, 'Usage of plastic straws in gastronomic industry has been falling since 2016', 'news about straws', 'straws source', 'short info straws'),
       ('2019-07-08 21:22:31', 5, 'With more eco-friendly approach to shopping, biggest EU markets noted an increase in sales of paper bags', 'news about paperbags', 'bags source', 'short info bags'),
       ('2022-06-27 12:28:31', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus1.', 'sample news1', 'farm source', 'Short info farms'),
       ('2021-06-27 15:15:42', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus2.', 'sample news2', 'fuel source', 'short info fuel'),
       ('2022-03-24 11:14:12', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus3.', 'sample news3', 'straws source', 'short info straws'),
       ('2022-07-08 21:22:31', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus4.', 'sample news4', 'bags source', 'short info bags'),
       ('2020-06-27 12:28:31', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus5.', 'sample news5', 'farm source', 'Short info farms'),
       ('2020-06-27 15:15:42', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus6.', 'sample news6', 'fuel source', 'short info fuel'),
       ('2020-03-24 11:14:12', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus7.', 'sample news7', 'straws source', 'short info straws'),
       ('2020-07-08 21:22:31', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus8.', 'sample news8', 'bags source', 'short info bags'),
       ('2019-06-27 12:28:31', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus9.', 'sample news9', 'farm source', 'Short info farms'),
       ('2019-06-27 15:15:42', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis porttitor lectus10.', 'sample news10', 'fuel source', 'short info fuel'),
       ('2019-03-24 11:14:12', 5, 'News about cyberspace infecting eco-friendly environment', 'cyber news', 'cyber source', 'short info cyber'),
       ('2019-07-08 21:22:31', 5, 'News about cake, baking and all that jazz.', 'cake news', 'cake source', 'short info cake'),
       ('2021-03-24 11:14:12', 2, 'Morbi iaculis ultricies magna, a ultrices mauris. Cras pulvinar nulla sit amet mattis scelerisque.', 'more ipsum', 'lorem source', 'short info lorem'),
       ('2021-07-08 21:22:31', 4, 'Morbi iaculis ultricies magna, a ultrices mauris. Cras pulvinar nulla sit amet mattis scelerisque.', 'more ipsum', 'ipsum source', 'short info ipsum'),
       ('2021-03-24 11:14:12', 5, 'Morbi iaculis ultricies magna, a ultrices mauris. Cras pulvinar nulla sit amet mattis scelerisque.', 'more lorem', 'lorem source', 'short info lorem'),
       ('2021-07-08 21:22:31', 5, 'Morbi iaculis ultricies magna, a ultrices mauris. Cras pulvinar nulla sit amet mattis scelerisque.', 'more ipsum', 'ipsum source', 'short info ipsum'),
       ('2020-03-24 11:14:12', 4, 'Nulla gravida sit amet odio et egestas.', 'news about straws', 'straws source', 'short info straws'),
       ('2020-07-08 21:22:31', 4, 'Nulla gravida sit amet odio et egestas.', 'news about paperbags', 'bags source', 'short info bags'),
       ('2021-03-24 11:14:12', 2, 'Nulla gravida sit amet odio et egestas.', 'news about straws', 'straws source', 'short info straws'),
       ('2021-07-08 21:22:31', 2, 'Nulla gravida sit amet odio et egestas.', 'news about paperbags', 'bags source', 'short info bags')