trigger:
  batch: true
  branches:
    include:
    - prod
  paths:
    exclude:
    - README.md

pr: none

variables:
- group: 'AzureCredentials'
- name: agentOS
  value: ubuntu-latest
  
- name: azKeyVault
  value: key-vault-greencity
- name: jsonSecret
  value: google-credentials
- name: jsonFile
  value: google-creds.json
- name: jsonLocation
  value: /site/wwwroot
  
- name: artifactName
  value: drop
- name: coreRepoName
  value: core
- name: onbootJarName
  value: app.jar
  
- name: azureSub
  value: GreenCity2022
- name: resourceGroup
  value: GreenCity
- name: coreServiceName
  value: greencity

- name: KEY_VAULT_NAME
  value: 'greencity-app'
- name: GREENCITY_SECRET_KEY_NAME
  value: 'LOGGING-ITA-TOKEN'

stages:
- stage: Build
  jobs: 
  - job: Build
    pool:
      vmImage: $(agentOS)
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureSub)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

          secret=$(az keyvault secret show --vault-name $KEY_VAULT_NAME --name $GREENCITY_SECRET_KEY_NAME --query value -o tsv)

          echo "<settings>" > $(Build.SourcesDirectory)/settings.xml
          echo "  <servers>" >> $(Build.SourcesDirectory)/settings.xml
          echo "    <server>" >> $(Build.SourcesDirectory)/settings.xml
          echo "      <id>github</id>" >> $(Build.SourcesDirectory)/settings.xml
          echo "      <username>ita-social-projects</username>" >> $(Build.SourcesDirectory)/settings.xml
          echo "      <password>$secret</password>" >> $(Build.SourcesDirectory)/settings.xml
          echo "    </server>" >> $(Build.SourcesDirectory)/settings.xml
          echo "  </servers>" >> $(Build.SourcesDirectory)/settings.xml
          echo "</settings>" >> $(Build.SourcesDirectory)/settings.xml
      env:
        AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
        AZURE_TENANT_ID: $(AZURE_TENANT_ID)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.21'
        mavenVersionOption: 'Default'
        options: '-Dmaven.test.skip=true -s $(Build.SourcesDirectory)/settings.xml'

    - script: mv $(coreRepoName)/target/*.jar $(coreRepoName)/target/$(onbootJarName)
      displayName: Rename core jar to app

    - script: |
        rm -f $(Build.SourcesDirectory)/settings.xml
      displayName: "Delete temporary settings.xml"

    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/target/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/greencity-chart'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/greencity-chart'

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: '$(artifactName)'
        
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: 'Dockerhub_Skyere'
        repository: 'skyere/greencity'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          prod-$(Build.BuildId)
          latest

- stage: Deploy
  jobs:
    - deployment: DeployCore
      displayName: Deploy core app service
      pool:
        vmImage: $(agentOS)
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: '$(artifactName)'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: HelmInstaller@0
              inputs:
                helmVersion: '3.9.0'
                installKubectl: true
                
            - task: HelmDeploy@0
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceConnection: 'production'
                namespace: 'default'
                command: 'upgrade'
                chartType: 'FilePath'
                chartPath: '$(System.ArtifactsDirectory)/drop/greencity-chart'
                releaseName: 'greencity'
                overrideValues: 'ingress.hostname=greencity.pick-up.city,deployment.image=skyere/greencity:prod-$(Build.BuildId),externalSecret.tenantId=20002ba7-39e2-4b00-adc3-3926758f2008,externalSecret.vaultUrl=https://greencity-values.vault.azure.net/'
                arguments: '--debug'
