package greencity.constant;

public final class SwaggerExampleModel {
    public static final String userProfileRequest =
        "User Profile Request\n"
            + "<div>\n"
            + "\t<ul class=\"tab\">\n"
            + "\t\t<li class=\"tabitem active\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"example\">Example Value</a>\n"
            + "\t\t</li>\n"
            + "\t\t<li class=\"tabitem\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"model\">Model</a>\n"
            + "\t\t</li>\n"
            + "\t</ul>\n"
            + "\t<pre>\n"
            + "{\n"
            + "  \"city\": \"string\",\n"
            + "  \"firstName\": \"string\",\n"
            + "  \"showEcoPlace\": true,\n"
            + "  \"showLocation\": true,\n"
            + "  \"showShoppingList\": true,\n"
            + "  \"socialNetworks\": [\n"
            + "    \"string with protocol, exmpl: https://www.google.com/search?q=spring&oq=spring\"\n"
            + "  ],\n"
            + "  \"userCredo\": \"string\"\n"
            + "}\n"
            + "\t</pre>\n"
            + "</div>";

    public static final String userProfilePictureDto =
        "User Profile Picture\n"
            + "<div>\n"
            + "\t<ul class=\"tab\">\n"
            + "\t\t<li class=\"tabitem active\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"example\">Example Value</a>\n"
            + "\t\t</li>\n"
            + "\t\t<li class=\"tabitem\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"model\">Model</a>\n"
            + "\t\t</li>\n"
            + "\t</ul>\n"
            + "\t<pre>\n"
            + "{\n"
            + "  \"id\": 0,\n"
            + "  \"profilePicturePath\": \"string\"\n"
            + "}\n"
            + "\t</pre>\n"
            + "</div>";

    public static final String addTipsAndTricksRequest =
        "Add tips & tricks request\n"
            + "<div>\n"
            + "\t<ul class=\"tab\">\n"
            + "\t\t<li class=\"tabitem active\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"example\">Example Value</a>\n"
            + "\t\t</li>\n"
            + "\t\t<li class=\"tabitem\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"model\">Model</a>\n"
            + "\t\t</li>\n"
            + "\t</ul>\n"
            + "\t<pre>\n"
            + "{\n"
            + "  \"image\": \"string\",\n"
            + "  \"source\": \"string\",\n"
            + "  \"tags\": [\n"
            + "    \"string\"\n"
            + "  ],\n"
            + "  \"text\": \"string\",\n"
            + "  \"title\": \"string\"\n"
            + "}"
            + "\t</pre>\n"
            + "</div>";

    public static final String addEcoNewsRequest =
        "Add Eco News Request\n"
            + "<div>\n"
            + "\t<ul class=\"tab\">\n"
            + "\t\t<li class=\"tabitem active\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"example\">Example Value</a>\n"
            + "\t\t</li>\n"
            + "\t\t<li class=\"tabitem\">\n"
            + "\t\t\t<a class=\"tablinks\" data-name=\"model\">Model</a>\n"
            + "\t\t</li>\n"
            + "\t</ul>\n"
            + "\t<pre>\n"
            + "{\n"
            + "  \"image\": \"string\",\n"
            + "  \"source\": \"string\",\n"
            + "  \"tags\": [\n"
            + "    \"string\"\n"
            + "  ],\n"
            + "  \"text\": \"string\",\n"
            + "  \"title\": \"string\"\n"
            + "}\n"
            + "\t</pre>\n"
            + "</div>";

    private SwaggerExampleModel() {
    }
}
