apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-greencity
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-greencity
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-greencity
        logs_app: greencity
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: {{ .Release.Name }}-greencity
          image: {{ .Values.deployment.image }}
          resources:
            requests:
              cpu: {{ .Values.deployment.requests.cpu }}
              memory: {{ .Values.deployment.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.limits.cpu }}
              memory: {{ .Values.deployment.limits.memory }}
          startupProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8080
            periodSeconds: 10
            failureThreshold: 20
          env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.secretName }}
                  key: AZURE-CLIENT-ID

            - name: AZURE_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.secretName }}
                  key: AZURE-SECRET-ID

            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.secretName }}
                  key: AZURE-TENANT-ID

            - name: KEY_VAULT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.secretName }}
                  key: KEY-VAULT-ENDPOINT
          ports:
            - containerPort: 8080
              name: tomcat
