apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-greencity-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:4200, https://www.greencity.cx.ua"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    allow-snippet-annotations: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* "^/actuator/prometheus") {
        return 403;
      }
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Release.Name }}-greencitygit
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ .Release.Name }}-greencity-service
            port: 
              number: 80
              

