package greencity.enums;

public enum NotificationType {
    ECONEWS_COMMENT_REPLY,
    ECONEWS_COMMENT_LIKE,
    ECONEWS_LIKE,
    ECONEWS_CREATED,
    ECONEWS_COMMENT_USER_TAG,
    ECONEWS_COMMENT,
    EVENT_COMMENT_REPLY,
    EVENT_COMMENT_LIKE,
    EVENT_COMMENT_USER_TAG,
    EVENT_CREATED,
    EVENT_CANCELED,
    EVENT_NAME_UPDATED,
    EVENT_UPDATED,
    EVENT_JOINED,
    EVENT_COMMENT,
    FRIEND_REQUEST_ACCEPTED,
    HABIT_LIKE,
    FRIEND_REQUEST_RECEIVED,
    HABIT_INVITE,
    HABIT_COMMENT,
    HABIT_COMMENT_REPLY,
    HABIT_COMMENT_USER_TAG
}
