package greencity.enums;

import lombok.Getter;

@Getter
public enum AchievementsCalculationEnum {
    // Habit Achievements
    ACQUIRED_HABIT_14_DAYS(20),
    ACQUIRED_HABIT_21_DAYS(30),
    ACQUIRED_HABIT_30_DAYS(40),
    UNDO_ACQUIRED_HABIT_14_DAYS(-20),
    UNDO_ACQUIRED_HABIT_21_DAYS(-30),
    UNDO_ACQUIRED_HABIT_30_DAYS(-40),

    // News Creation Achievements
    CREATED_5_NEWS(5),
    CREATED_10_NEWS(10),
    CREATED_25_NEWS(25),
    CREATED_50_NEWS(50),
    CREATED_100_NEWS(100),
    DELETE_5_NEWS(-5),
    DELETE_10_NEWS(-10),
    DELETE_25_NEWS(-25),
    DELETE_50_NEWS(-50),
    DELETE_100_NEWS(-100),

    // Comment or Reply Achievements
    COMMENT_OR_REPLY_5_TIMES(10),
    COMMENT_OR_REPLY_10_TIMES(20),
    COMMENT_OR_REPLY_25_TIMES(50),
    COMMENT_OR_REPLY_50_TIMES(100),
    COMMENT_OR_REPLY_100_TIMES(200),
    DELETE_COMMENT_OR_REPLY_5_TIMES(-10),
    DELETE_COMMENT_OR_REPLY_10_TIMES(-20),
    DELETE_COMMENT_OR_REPLY_25_TIMES(-50),
    DELETE_COMMENT_OR_REPLY_50_TIMES(-100),
    DELETE_COMMENT_OR_REPLY_100_TIMES(-200),

    // Like Achievements
    LIKE_COMMENT_OR_REPLY_1_TIMES(10),
    LIKE_COMMENT_OR_REPLY_5_TIMES(20),
    LIKE_COMMENT_OR_REPLY_10_TIMES(30),
    LIKE_COMMENT_OR_REPLY_25_TIMES(40),
    LIKE_COMMENT_OR_REPLY_50_TIMES(50),
    LIKE_COMMENT_OR_REPLY_100_TIMES(60),
    UNLIKE_COMMENT_OR_REPLY_1_TIMES(-10),
    UNLIKE_COMMENT_OR_REPLY_5_TIMES(-20),
    UNLIKE_COMMENT_OR_REPLY_10_TIMES(-30),
    UNLIKE_COMMENT_OR_REPLY_25_TIMES(-40),
    UNLIKE_COMMENT_OR_REPLY_50_TIMES(-50),
    UNLIKE_COMMENT_OR_REPLY_100_TIMES(-60),

    // Share Achievements
    SHARE_NEWS_1_TIMES(20),
    SHARE_NEWS_5_TIMES(40),
    SHARE_NEWS_10_TIMES(60),
    SHARE_NEWS_25_TIMES(80),
    SHARE_NEWS_50_TIMES(100),
    SHARE_NEWS_100_TIMES(120),
    UNDO_SHARE_NEWS_1_TIMES(-20),
    UNDO_SHARE_NEWS_5_TIMES(-40),
    UNDO_SHARE_NEWS_10_TIMES(-60),
    UNDO_SHARE_NEWS_25_TIMES(-80),
    UNDO_SHARE_NEWS_50_TIMES(-100),
    UNDO_SHARE_NEWS_100_TIMES(-120),

    // First Achievements
    FIRST_5_ACHIEVEMENTS(20),
    FIRST_10_ACHIEVEMENTS(40),
    FIRST_15_ACHIEVEMENTS(60),
    FIRST_20_ACHIEVEMENTS(80);

    private final long ratingPoints;

    AchievementsCalculationEnum(long ratingPoints) {
        this.ratingPoints = ratingPoints;
    }
}
