package greencity.enums;

public enum TypeOfEmailNotification {
    NEWS_COMMENTED,
    NEWS_LIKED,
    REPLY,
    COMMENT_LIKED,
    EVENT_CREATED,
    EVENT_COMMENTED,
    EVENT_LIKED,
    EVENT_CANCELED,
    EVENT_UPDATED,
    EVENT_JOINED,
    FRIENDSHIP_REQUEST,
    FRIENDSHIP_REQUEST_ACCEPTED,
    HABIT_COMMENTED,
    HABIT_LIKED,
    HABIT_INVITED
}
