environment: dev

deployment:
  replicas: 1
  image: skyere/greencity:latest
  requests:
    cpu: 10m
    memory: 200Mi
  limits:
    cpu: 2
    memory: 1024Mi

externalSecret:
  secretName: greencity-secret

service:
  type: ClusterIP

# You need Nginx ingress controller and cert manager already installed
# https://kubernetes.github.io/ingress-nginx/deploy/
# https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions
ingress:
  enable_cors: true

  # Example: "https://origin-site.com:4443, http://origin-site.com, https://example.org:1199"
  # "https://*.origin-site.com:4443, http://*.origin-site.com"
  # If not set will be used "*" instead. Example: cors_allow_origin: ""
  cors_allow_origin: https://ita-social-projects.github.io/GreenCityClient/, http://localhost:4200, http://localhost:4200/*, https://www.testgreencity.ga/GreenCityClient/

  # Only when cors_allow_origin is not "*"
  cors_allow_credentials: "true"

  hostname: greencity-test.testgreencity.ga
  
