# Datasource
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# Liquibase
spring.liquibase.url=${DATASOURCE_URL}
spring.liquibase.user=${DATASOURCE_USER}
spring.liquibase.password=${DATASOURCE_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

# Mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_ADDRESS}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
address=http://core:8080
client.address=http://localhost:4200
econews.address=http://localhost:4200/welcome
sender.email.address=${EMAIL_ADDRESS}
google.clientId=${GOOGLE_CLIENT_ID}

# Token expiration time
accessTokenValidTimeInMinutes=120
refreshTokenValidTimeInMinutes=600
tokenKey=123123123123123123123123123123123123
verifyEmailTimeHour=24

# Logger
logging.level.root=info
logging.level.io.swagger.models.parameters.AbstractSerializableParameter=ERROR
logging.level.greencity.exception.handler.CustomExceptionHandler=trace
logging.pattern.console=%d{"yyyy/MM/dd HH:mm:ss,SSS"} %magenta([%thread]) %highlight(%-5level) %M\\(%F:%L\\) - %msg%n

# Cache
spring.cache.caffeine.spec=maximumSize=50, expireAfterAccess=86400s

# Time after a user last activity time to check if a user is online
greencity.time.after.last.activity=300000

#Thymeleaf
spring.thymeleaf.cache=false

#RestTemplate
greencityuser.server.address = http://user:8060
greencityubs.server.address = http://ubs-service:8050

#WebClient
webclient.connection-timeout-millis=5000
webclient.response-timeout-millis=5000

#AzureCloudStorage
azure.connection.string=${AZURE_CONNECTION_STRING}
azure.container.name=${AZURE_CONTAINER_NAME}

pg.dump.path=pg_dump

# Cron
cron.sendContentToSubscribers=${CRON_SEND_CONTENT_TO_SUBSCRIBERS:0 0 20 * * SAT}
cron.generateEcoNews=${CRON_GENERATE_ECO_NEWS:0 0 20 * * SAT}
cron.calculateRelevance=${CRON_CALCULATE_RELEVANCE:0 0 0/3 * * *}

# OpenAI
openai.api.key=${OPEN_AI_API_KEY}
openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.model=gpt-4o-mini
openai.api.url.embedding=https://api.openai.com/v1/embeddings
openai.api.model.embedding=text-embedding-3-small
openai.api.dimensions.tokens=300
openai.api.max_completion_tokens=1500
openai.api.temperature=0.5

# QuartzProperties
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.schema=classpath:db/changelog/logs/ch-add-quartz-tables.xml
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.generation.languages=ua

# EcoNews Relevance
greencity.relevance.enabled=${ECONEWS_RELEVANCE_ENABLED:false}
#mix of "strong relevant:weak relevant:non-relevant" news
greencity.relevant.news.ratio=3:6:1
#impact of "titles semantics:tags" on relevance calculation
greencity.titles.tags.scores.weights=0.5:0.5
#impact of "liked news:assigned habits:liked events" on relevance calculation
greencity.econews.habits.events.tags.weights=0.6:0.2:0.2
#"upper" and "lower" thresholds for "strong relevant" above, "non-relevant" under and "weak relevant" between
greencity.relevance.strengths.threshold=0.6:0.2
greencity.cache.relevance.expiration.time=60