# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

address=http://localhost:8080
google.maps.api.key=""

#Security Cookies
use-secure-cookies=${USE_SECURE_COOKIES:false}

#RestTemplate
greencityuser.server.address=http://localhost:8080
greencityubs.server.address = http://localhost:8050

# Email for service-to-service communication with GreenCityUser
client.address=http://localhost:4200
spring.liquibase.parameters.service-email=test@greencity.ua

# Token expiration time
tokenKey=1
accessTokenValidTimeInMinutes=120
refreshTokenValidTimeInMinutes=600
verifyEmailTimeHour=24

#AzureCloudStorage
azure.connection.string=test
azure.container.name=test

pg.dump.path=pg_dump

# Cron
cron.sendContentToSubscribers=${CRON_SEND_CONTENT_TO_SUBSCRIBERS:0 0 20 * * SAT}

# OpenAI
openai.api.key=${OPEN_AI_API_KEY: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}
openai.api.url=https://api.openai.com/v1/chat/completions