# Datasource
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# Liquibase
spring.liquibase.url=${DATASOURCE_URL}
spring.liquibase.user=${DATASOURCE_USER}
spring.liquibase.password=${DATASOURCE_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${DIALECT}

# Mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_ADDRESS}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
address=http://core:8080
client.address=http://localhost:4200
econews.address=http://localhost:4200/welcome
sender.email.address=${EMAIL_ADDRESS}
google.clientId=${GOOGLE_CLIENT_ID}

# Token expiration time
accessTokenValidTimeInMinutes=120
refreshTokenValidTimeInMinutes=600
tokenKey=123123123123123123123123123123123123
verifyEmailTimeHour=24

# Logger
logging.level.root=info
logging.level.io.swagger.models.parameters.AbstractSerializableParameter=ERROR
logging.level.greencity.exception.handler.CustomExceptionHandler=trace
logging.pattern.console=%d{"yyyy/MM/dd HH:mm:ss,SSS"} %magenta([%thread]) %highlight(%-5level) %M\\(%F:%L\\) - %msg%n

# Cache
spring.cache.caffeine.spec=maximumSize=50, expireAfterAccess=86400s

# Time after a user last activity time to check if a user is online
greencity.time.after.last.activity=300000

#Thymeleaf
spring.thymeleaf.cache=false

#RestTemplate
greencityuser.server.address = http://user:8060

#AzureCloudStorage
azure.connection.string=${AZURE_CONNECTION_STRING}
azure.container.name=${AZURE_CONTAINER_NAME}

pg.dump.path=pg_dump

# Cron
cron.sendContentToSubscribers=${CRON_SEND_CONTENT_TO_SUBSCRIBERS:0 0 20 * * SAT}

# OpenAI
openai.api.key=${OPEN_AI_API_KEY}
openai.api.url=https://api.openai.com/v1/chat/completions

## QuartzProperties
spring.quartz.job-store-type= jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.schema=classpath:db/changelog/logs/ch-add-quartz-tables.xml
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.plugin.shutdownHook.class=org.quartz.plugins.management.ShutdownHookPlugin
spring.quartz.properties.org.quartz.plugin.shutdownHook.cleanShutdown=TRUE
spring.quartz.properties.org.quartz.jobStore.dataSource=myDS
spring.quartz.properties.org.quartz.dataSource.myDS.driver=org.postgresql.Driver
spring.quartz.properties.org.quartz.dataSource.myDS.URL=${DATASOURCE_URL}
spring.quartz.properties.org.quartz.dataSource.myDS.user=${DATASOURCE_USER}
spring.quartz.properties.org.quartz.dataSource.myDS.password=${DATASOURCE_PASSWORD}
spring.quartz.properties.org.quartz.dataSource.myDS.maxConnections=5
