spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${KEY_VAULT_ENDPOINT}
spring.cloud.azure.keyvault.secret.property-sources[0].refresh-interval=15m

#Azure Connection
spring.cloud.azure.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.credential.client-secret=${AZURE_SECRET_ID}
spring.cloud.azure.profile.tenant-id=${AZURE_TENANT_ID}

# Actuator endpoints
management.endpoints.web.exposure.include=health, info, metrics, prometheus

# Datasource
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximumPoolSize=${DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
server.port=8080

# Liquibase
spring.liquibase.url=${DATASOURCE_URL}
spring.liquibase.user=${DATASOURCE_USERNAME}
spring.liquibase.password=${DATASOURCE_PASSWORD}
spring.liquibase.enabled=${LIQUIBASE_ENABLED}
spring.liquibase.change-log=${LIQUIBASE_CHANGE_LOG}

# Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Mail sender
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

address=${GREENCITY_SERVER_ADDRESS}
client.address=${CLIENT_ADDRESS}

# Tokens expiration time
security.jwt.access-token.expiration-minutes=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
security.jwt.secret-key=${JWT_SECRET_KEY}

# Logger
logging.level.root=${LOGGING_LEVEL_ROOT:debug}
logging.level.greencity.exception.handler.CustomExceptionHandler=${LOGGING_LEVEL_EXCEPTION_HANDLER:ERROR}
logging.file.path=${LOGGING_FILE_PATH:logs}
logging.file.name=${LOGGING_FILE_NAME:logs/log.log}
logging.pattern.file=%d{"yyyy/MM/dd HH:mm:ss,SSS"} %magenta([%thread]) %highlight(%-5level) %M\\(%F:%L\\) - %msg%n

# Cache
spring.cache.caffeine.spec=${CACHE_CAFFEINE_SPEC}

#RestTemplate
greencityuser.server.address = ${GREENCITYUSER_SERVER_ADDRESS}
greencityubs.server.address = ${GREENCITY_UBS_SERVER_ADDRESS}

#WebClient
webclient.connection-timeout-millis=${WEBCLIENT_CONNECTION_TIMEOUT}
webclient.response-timeout-millis=${WEBCLIENT_RESPONSE_TIMEOUT}

#AzureCloudStorage
azure.connection.string=${AZURE_CONNECTION_STRING}
azure.container.name=${AZURE_CONTAINER_NAME}

pg.dump.path=pg_dump

# Cron
cron.sendContentToSubscribers=0 0 20 * * SAT
cron.generateEcoNews=0 0 20 * * SAT
cron.calculateRelevance=0 0 0/3 * * *

# OpenAI
openai.api.key=${OPEN_AI_API_KEY}
openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.model=gpt-4o-mini
openai.api.url.embedding=https://api.openai.com/v1/embeddings
openai.api.model.embedding=text-embedding-3-small
openai.api.dimensions.tokens=300
openai.api.max_completion_tokens=1500
openai.api.temperature=0.5

# QuartzProperties
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.schema=classpath:db/changelog/logs/ch-add-quartz-tables.xml
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.generation.languages=uk

# EcoNews Relevance
greencity.relevance.enabled=${ECONEWS_RELEVANCE_ENABLED}
#mix of "strong relevant:weak relevant:non-relevant" news
greencity.relevant.news.ratio=3:6:1
#impact of "titles semantics:tags" on relevance calculation
greencity.titles.tags.scores.weights=0.5:0.5
#impact of "liked news:assigned habits:liked events" on relevance calculation
greencity.econews.habits.events.tags.weights=0.6:0.2:0.2
#"upper" and "lower" thresholds for "strong relevant" above, "non-relevant" under and "weak relevant" between
greencity.relevance.strengths.threshold=0.6:0.2
greencity.cache.relevance.expiration.time=60

# File upload limit
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_FILE_SIZE}
server.tomcat.max-http-form-post-size=${TOMCAT_MAX_HTTP_FORM_POST_SIZE}
max-multipart-comment-image-size=10MB

#Security Cookies
use-secure-cookies=false

# Email for service-to-service communication with GreenCityUser
spring.liquibase.parameters.service-email=${SYSTEM_EMAIL_ADDRESS}

# Feign FallbackFactories
feign.hystrix.enabled=true
hystrix.command.default.execution.isolation.strategy=SEMAPHORE
hystrix.shareSecurityContext=true

# change default hystrix timeout to 10 seconds
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=20000
ribbon.ConnectTimeout=20000
ribbon.ReadTimeout=20000

greencity.authorization.googleApiKey=${GOOGLE_API_KEY}
google.maps.api.key=${GOOGLE_MAP_API_KEY}

# Swagger configuration
springdoc.paths-to-match=/**
springdoc.paths-to-exclude=/management/**
springdoc.packages-to-scan=greencity.controller,com.softserve.ldm.controller
springdoc.swagger-ui.doc-expansion=none

#WebSockets
spring.messaging.stomp.websocket.allowed-origins=\
 https://www.greencity.cx.ua, \
  https://www.greencity.cx.ua/, \
  https://www.greencity.cx.ua/*, \
  https://greencity.greencity.cx.ua, \
  https://greencity.greencity.cx.ua/, \
  https://greencity.greencity.cx.ua/*, \
  https://greencity-user.greencity.cx.ua, \
  https://greencity-user.greencity.cx.ua/, \
  https://greencity-user.greencity.cx.ua/*, \
  https://www.pick-up.city, \
  https://www.pick-up.city/, \
  https://www.pick-up.city/*, \
  http://localhost:4200, \
  http://localhost:4200/, \
  http://localhost:4200/*, \
  http://localhost:4205, \
  http://localhost:4200/, \
  http://localhost:4205/*

server.tomcat.relaxed-query-chars=<, >, [, \,, ], ^, `, {, |, }
valid.endpoints=/friends/not-friends-yet,/friends/friendRequests, /friends/{friendId}, /ai/forecast/, /ai/generate/eco-news, /management/, \
  /achievements/categories, /achievements, /achievements/achieve, /achievements/count, /categories, /commit-info/, /custom/to-do-list-items/{userId}/{habitId} \
  /custom/to-do-list-items/{userId}/{habitAssignId}/custom-to-do-list-items, /custom/to-do-list-items/{userId}/custom-to-do-list-items \
  /custom/to-do-list-items/{userId}/done, /custom/to-do-list-items/{userId}/custom-to-do-list-items, /database/backup, /database/backupFiles \
  /eco-news/{ecoNewsId}/comments, /eco-news/{ecoNewsId}/comments/count, /eco-news/comments/{parentCommentId}/replies/active, /eco-news/comments/{parentCommentId}/replies/active/count \
  /eco-news/comments/{id}, /eco-news/comments, /eco-news/comments/like, /exo-news/comments/dislike, /eco-news/likeAndCount, /eco-news/{ecoNewsId}/comments/active \
  /eco-news/getUsersToTagInComment, /events/{eventId}/comments, /events/comments/{commentId}, /events/{eventId}/comments/count \
  /events/comments/{commentId}, /events/comments/{parentCommentId}/replies/active, /events/comments/{parentCommentId}/replies/count,  /events/comments/like/{commentId} \
  /events/comments/dislike/{commentId}, /events/{eventId}, /events/{eventId}/attenders, /events/{eventId}/favorites, /events/{eventId}/like \
  /events/{eventId}/dislike, /events/{eventId}/likes/count, /events/{eventId}/dislikes/count, /events/{eventId}/likes, /events/{eventId}/dislikes \
  /events/{eventId}/ratings, /events/{eventId}/attenders, /events/addresses, /events/attenders/count, /events/organizers/count, /events/{eventId}/addToRequested \
  /events/{eventId}/removeFromRequested, /events/{eventId}/requested-users, /events/{eventId}/requested-users/{userId}/approve, /events/{eventId}/requested-users/{userId}/decline \
  /fact-of-the-day/random, /fact-of-the-day/random/by-tags, /favorite_place/, /favorite_place/favorite_place/, favorite_place/favorite/{placeId} \
  /files, /friends/{friendId}, /friends/, /friends, /friends/{friendId}/declineFriend, /friends/user/{userId}, /friends/{userId}/all-user-friends \
  /friends/not-friends-yet, /friends/recommended-friends, /friends/friendRequests, /friends/mutual-friends, /friends/{friendId}/cancelRequest, /friends/user-data-as-friend/{friendId} \
  /management/displayGraph, /habit/assign/{habitId}, /habit/assign/{habitId}/custom, /habit/assign{habitAssignId}/update-status-and-duration \
  /habit/assign/{habitAssignId}/update-habit-duration, /habit/assign/allForCurrentUser, /habit/assign/allUser/{userId}, /habit/assign/allMutualHabits/{userId} \
  /habit/assign/myHabits/{userId}, /habit/assign/{habitAssignId}/allUserAndCustomList \
  /habit/assign/allUserAndCustomToDoListsInprogress, /habit/assign/{habitId}/all, /habit/assign/{habitId}/active, /habit/assign/{habitAssignId}/more \
  /habit/assign/{habitAssignId}/enroll/{date}, /habit/assign/active/{date}, habit/assign/activity/{from}/to/{to}, habit/assign/delete/{habitAssignId} \
  /habit/assign/{habitAssignId}/updateProgressNotificationHasDisplayed, /habit/assign/{habitId}/invite, /habit/assign/confirm/{habitAssignId}, habit/assign/{habitAssignId}/friends/habit-duration-info \
  /habits/{habitId}/comments, /habits/comments/{id}, /habits/comments/{parentCommentId}/replies/active, /habits/{habitId}/comments/count, /habits/comments/{parentCommentId}/replies/active/count \
  /habits/comments/active, /habits/comments/like, /habits/comments/dislike, /habits/comments, /habits/comments/{id}, /habit/{id}, /habit , /habit/, /habit/my \
  /habit/all/{friendId}, /habit/allMutualHabits/{friendId}, /habit/{id}/to-do-list, /habit/tags/search, /habit/search, /habit/tags, /habit/custom \
  /habit/{habitAssignId}/friends/profile-pictures, /habit/update/{habitId}, /habit/delete/{customHabitId}, /habit/like, /habit/dislike, /habit/{habitId}/favorites, /habit/favorites \
  /habit/friends, /habit/invite/{invitationId}/accept, /habit/invite/{invitationId}/reject, /habit/statistic/{habitId}, /habit/statistic/assign/{habitAssignId} \
  /habit/invite/{id}, /habit/invite/todayStatisticsForAllHabitItems, /habit/invite/acquired/count, /habit/in-progress/count, /languages/codes \
  /management/achievement, /management/achievement/, /management/achievement/{id}, /management/achievement/deleteAll, /management/achievement/statistics \
  /management/achievement/statistics/, /management/achievement/statistics/by-category, /management/achievement/statistics/by-activity, /management, /, /management/login \
  /management/eco-news, /management/eco-news/, /management/eco-news/delete, /management/eco-news/deleteAll, /management/eco-news/find/{id}, /management/eco-news/{id} \
  /management/eco-news/tags, /management/eco-news/save, /management/eco-news/{id}/likes, /management/eco-news/{id}/dislikes, /management/eco-news/hide \
  /management/eco-news/show, /management/econews/statistics, /management/econews/statistics/tags, /management/econews/statistics/user/activity \
  /management/events, /management/events/create-event, /management/events/edit/{id}, /management/factoftheday, /management/factoftheday/findAll, /management/factoftheday/ ,/management/factoftheday/deleteAll \
  /management/factoftheday/tags, /management/habits, /management/habits/{id}/find, /management/habits/{id}, /management/habits/save, /management/habits/update \
  /management/habits/delete, /management/habits/deleteAll, /management/habits/switch-deleted-status/{id}, /management/habits/switch-custom-status/{id} \
  /management/habit/statistics, /management/habit/statistics/interest, /management/habit/statistics/habit-behavior, /management/habit/statistics/user-interaction \
  /management/habit-to-do-list, /management/habit-to-do-list/deleteAll/, /management/habit-to-do-list/addAll/, /management/habit-to-do-list/delete/, /management/habit-to-do-list/add/ \
  /management/places, /management/places/find, /management/places/deleteAll, /management/rating/calculation, /management/rating/calculation/{id}, /management/rating/calculation/deleted \
  /management/rating/calculation/restore/{id}, /management/rating, /management/rating/export, /management/rating/exportFiltered, /management/socialnetworkimages, /management/socialnetworkimages/ \
  /management/socialnetworkimages/delete, /management/socialnetworkimages/deleteAll, /management/socialnetworkimages/find, /management/socialnetworkimages/ \
  /management/tags, /management/tags/{id}, /management/tags/search, /management/to-do-list-items, /management/to-do-list-items/{id}, /management/to-do-list-items/deleteAll \
  /management/to-do-list-items/unlink/{habitId}, /management/to-do-list-items/filter, /management/users, /management/users/register, /management/users/ \
  /management/users/findById, /management/users/{id}/friends, /management/users/management/users, /management/users/{id}/status, /management/users/deactivate \
  /management/users/lang, /management/users/activate, /management/users/reasons, /management/users/deactivateAll, /management/users/search, /management/users/updateToDoItem/{habitId}/{itemId} \
  /management/users/filter-save, /management/users/select-filter/{id}, /management/users/{id}/delete-filter, /management/users/{id}, /management/users/{id}/updateUserStatus \
  /management/users/{id}/updateUserRole, /management/user/statistics, /management/user/statistics/registration, /management/user/statistics/roles, /management/user/statistics/statuses \
  /management/user/statistics/locations, /management/user/statistics/preferences, /notifications, /notifications/{notificationId}/viewNotification, /notifications/{notificationId}/unreadNotification \
  /notifications/{notificationId, /notifications/notifications, /place/{placeId}/comments, comments/{id}, comments, /place/propose, /place/update, /place/info/{id}, /place/info/favorite/{placeId} \
  /place/save/favorite/, /place/getListPlaceLocationByMapsBounds, /place/{status}, /place/filter, /place/status, /place/filter/predicate, /place/about/{id}, /place/statuses \
  /place/{id}, /place, /place/v2/filteredPlacesCategories, /place/v2/save, /place/all, /chat, /search/eco-news, /search/events, /search/places, /social-networks/image, /social-networks, /specification \
  /subscriptions, /subscriptions/{unsubscribeToken}, /tags/search, /tags/v2/search, /user/to-do-list-items/habits/{habitId}/to-do-list, /user/to-do-list-items, /user/to-do-list-items/{userToDoListItemId} \
  /user/to-do-list-items/{userToDoListItemId}/status/{status}, /user/to-do-list-items/user-to-do-list-items, /user/to-do-list-items/{userId}/get-all-inprogress, /token \
  /ai/forecast

valid.statuses=ACTIVE, COMPLETED, PENDING, ACCEPTED, REJECTED, \
               BLOCKED, DEACTIVATED, ACTIVATED, CREATED, ORIGINAL, \
               EDITED, DELETED, DONE, DISABLED, INPROGRESS, DELETE



